### ISSUE TITLE
household_objects database file link not working

### ISSUE THREAD

**Issue by nehagarg** [ros-interactive-manipulation/household_objects_database#12]
I am trying to setup household objects database on my local machine following the instructions from ros tutorial here:
http://wiki.ros.org/household_objects_database/Tutorials/Install%20the%20household_objects%20database%20on%20your%20local%20database%20server

This tutorial provides a link for downloading object database file which is : http://wiki.ros.org/household_objects_database/Tutorials

However that link is not working. Can you please check if the server is still live or is there any other link from where I can download the database?

Thanks.

**Comment by mateiciocarlie** [comment]
Looks like code.ros.org is down. I don't know it it's temporary or permanent...

If it's been permanently decomissioned, I'll try to see if we can move the data files somewhere else. Sorry, but there might not be a quick fix for this one.

**Comment by nehagarg** [comment]
The link is up again. Thanks.
