### ISSUE TITLE
Concerned about status of code.ros.org

### ISSUE THREAD

**Issue by ablasdel** [ros-interactive-manipulation/household_objects_database#14]
Currently to my knowledge the household_objects database backups are only hosted here: https://code.ros.org/svn/data/trunk/household_objects/

But I thought code.ros.org was EOL?

If not would creating a repo inside of ros-interactive-manipulation to store these db-backups be kosher?

Perhaps I am just pointed in the wrong direction, Is there another storage location that has more recent versions of the database available?

**Comment by mateiciocarlie** [comment]
You are right - we do need a better place to store those binary backup files...

Do you know if Github if happy storing reasonably big binaries? If so, a repo inside here would sound great to me.

**Comment by ablasdel** [comment]
The trouble with binaries on GitHub is they don't diff. Here are the actual "restrictions": https://help.github.com/articles/what-is-my-disk-quota

I'll look into this tomorrow.

**Comment by ablasdel** [comment]
We will probably run into issues with this guy: household_objects-experimental.backup (529 MB)
The others will probably not be an issue

What is the experimental one? Is it the latest upload of the Willow DB? Which of these should be used to start spin up new instances? I thought 0.6_fuerte was the best start point since experimental sounds like it wasn't intended to be stable.

**Comment by mateiciocarlie** [comment]
Yes - that's the latest upload. I would start new instances from that - it needs to be cleansed of "experimental" stuff (though I don't exactly remember what that is) and then it will be a more manageable size...

**Comment by ablasdel** [comment]
Ok I will look and see where the size is coming from and try to trim a bit. If I can get it under 100 meg then this is a workable solution.

**Comment by ablasdel** [comment]
@mateiciocarlie Can you shed some light on what the new "view" table is in the database? The blobs in there account for the majority of the extra size of the database and I have yet to find where the table is used in the code. Is it safe to just truncate this table?

**Comment by mateiciocarlie** [comment]
Oh, that's a leftover from some old experiments... It can safely go away.

**Comment by ablasdel** [comment]
Ok I think this will do it: https://github.com/ros-interactive-manipulation/household_objects_database_backups

the 0.7 groovy version is the experimental dump with the view table dropped and all the experimental grippers and their related data removed from the hand, grasp & optimization tables.

I will put this on the wiki as the new primary location to grab this info. If there are any remaining issues we can open another issue on the above repo.
